name: responde_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: MonsterGame
      fonts:
        - asset: assets/MonsterGame.ttf
    - family: FredokaOne
      fonts:
        - asset: assets/FredokaOne.ttf