name: responde_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  circular_countdown_timer: ^0.2.4
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg.png
    - assets/cards.png
    - assets/questions.json

    - assets/sounds/acerto1.wav
    - assets/sounds/background.wav
    - assets/sounds/clique1.wav
    - assets/sounds/clique2.wav
    - assets/sounds/clique3.wav
    - assets/sounds/clique4.wav
    - assets/sounds/erro1.wav
    - assets/sounds/erro2.wav

  
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/FredokaOne.ttf