name: responde_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  circular_countdown_timer: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/bg.png
    - assets/cards.png
    - assets/questions.json
  
  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/FredokaOne.ttf